#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerAruduino
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdventureWorks")]
	public partial class EMSdatacontextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertArduino2(Arduino2 instance);
    partial void UpdateArduino2(Arduino2 instance);
    partial void DeleteArduino2(Arduino2 instance);
    #endregion
		
		public EMSdatacontextDataContext() : 
				base(global::ControllerAruduino.Properties.Settings.Default.AdventureWorksConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EMSdatacontextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EMSdatacontextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EMSdatacontextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EMSdatacontextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Arduino2> Arduino2s
		{
			get
			{
				return this.GetTable<Arduino2>();
			}
		}
		
		public System.Data.Linq.Table<M_VITRI_V> M_VITRI_Vs
		{
			get
			{
				return this.GetTable<M_VITRI_V>();
			}
		}
		
		public System.Data.Linq.Table<M_VITRI_V2> M_VITRI_V2s
		{
			get
			{
				return this.GetTable<M_VITRI_V2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Arduino2")]
	public partial class Arduino2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_ptdien;
		
		private string _Pin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_ptdienChanging(int value);
    partial void OnId_ptdienChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    #endregion
		
		public Arduino2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_ptdien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_ptdien
		{
			get
			{
				return this._Id_ptdien;
			}
			set
			{
				if ((this._Id_ptdien != value))
				{
					this.OnId_ptdienChanging(value);
					this.SendPropertyChanging();
					this._Id_ptdien = value;
					this.SendPropertyChanged("Id_ptdien");
					this.OnId_ptdienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_VITRI_V")]
	public partial class M_VITRI_V
	{
		
		private int _ID_PTDIEN;
		
		private string _MA_DVQLY;
		
		private string _TEN_PTDIEN;
		
		private string _LOAI_PTDIEN;
		
		private string _MA_CAPDA;
		
		private string _MA_CMIS;
		
		private bool _LEFT_TRANGTHAI;
		
		private bool _RIGHT_TRANGTHAI;
		
		private System.Nullable<System.DateTime> _NGAY_CAP_NHAT;
		
		public M_VITRI_V()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PTDIEN", DbType="Int NOT NULL")]
		public int ID_PTDIEN
		{
			get
			{
				return this._ID_PTDIEN;
			}
			set
			{
				if ((this._ID_PTDIEN != value))
				{
					this._ID_PTDIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DVQLY", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string MA_DVQLY
		{
			get
			{
				return this._MA_DVQLY;
			}
			set
			{
				if ((this._MA_DVQLY != value))
				{
					this._MA_DVQLY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_PTDIEN", DbType="NVarChar(150)")]
		public string TEN_PTDIEN
		{
			get
			{
				return this._TEN_PTDIEN;
			}
			set
			{
				if ((this._TEN_PTDIEN != value))
				{
					this._TEN_PTDIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAI_PTDIEN", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string LOAI_PTDIEN
		{
			get
			{
				return this._LOAI_PTDIEN;
			}
			set
			{
				if ((this._LOAI_PTDIEN != value))
				{
					this._LOAI_PTDIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CAPDA", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string MA_CAPDA
		{
			get
			{
				return this._MA_CAPDA;
			}
			set
			{
				if ((this._MA_CAPDA != value))
				{
					this._MA_CAPDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CMIS", DbType="NVarChar(50)")]
		public string MA_CMIS
		{
			get
			{
				return this._MA_CMIS;
			}
			set
			{
				if ((this._MA_CMIS != value))
				{
					this._MA_CMIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEFT_TRANGTHAI", DbType="Bit NOT NULL")]
		public bool LEFT_TRANGTHAI
		{
			get
			{
				return this._LEFT_TRANGTHAI;
			}
			set
			{
				if ((this._LEFT_TRANGTHAI != value))
				{
					this._LEFT_TRANGTHAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RIGHT_TRANGTHAI", DbType="Bit NOT NULL")]
		public bool RIGHT_TRANGTHAI
		{
			get
			{
				return this._RIGHT_TRANGTHAI;
			}
			set
			{
				if ((this._RIGHT_TRANGTHAI != value))
				{
					this._RIGHT_TRANGTHAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_CAP_NHAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_CAP_NHAT
		{
			get
			{
				return this._NGAY_CAP_NHAT;
			}
			set
			{
				if ((this._NGAY_CAP_NHAT != value))
				{
					this._NGAY_CAP_NHAT = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_VITRI_V2")]
	public partial class M_VITRI_V2
	{
		
		private int _ID_PTDIEN;
		
		private string _MA_DVQLY;
		
		private string _MA_PTDIEN;
		
		private string _MA_PMIS;
		
		private System.Data.Linq.Binary _TOA_DO;
		
		private string _MA_CAPDA;
		
		private string _TEN_PTDIEN;
		
		private string _LOAI_PTDIEN;
		
		private string _MA_PMISCHA;
		
		private string _MA_SCADA;
		
		private string _MA_CMIS;
		
		private System.Nullable<int> _TRANG_THAI;
		
		private System.Nullable<System.DateTime> _THOI_DIEM;
		
		public M_VITRI_V2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PTDIEN", DbType="Int NOT NULL")]
		public int ID_PTDIEN
		{
			get
			{
				return this._ID_PTDIEN;
			}
			set
			{
				if ((this._ID_PTDIEN != value))
				{
					this._ID_PTDIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DVQLY", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string MA_DVQLY
		{
			get
			{
				return this._MA_DVQLY;
			}
			set
			{
				if ((this._MA_DVQLY != value))
				{
					this._MA_DVQLY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_PTDIEN", DbType="NVarChar(9)")]
		public string MA_PTDIEN
		{
			get
			{
				return this._MA_PTDIEN;
			}
			set
			{
				if ((this._MA_PTDIEN != value))
				{
					this._MA_PTDIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_PMIS", DbType="NVarChar(50)")]
		public string MA_PMIS
		{
			get
			{
				return this._MA_PMIS;
			}
			set
			{
				if ((this._MA_PMIS != value))
				{
					this._MA_PMIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOA_DO", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary TOA_DO
		{
			get
			{
				return this._TOA_DO;
			}
			set
			{
				if ((this._TOA_DO != value))
				{
					this._TOA_DO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CAPDA", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string MA_CAPDA
		{
			get
			{
				return this._MA_CAPDA;
			}
			set
			{
				if ((this._MA_CAPDA != value))
				{
					this._MA_CAPDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_PTDIEN", DbType="NVarChar(150)")]
		public string TEN_PTDIEN
		{
			get
			{
				return this._TEN_PTDIEN;
			}
			set
			{
				if ((this._TEN_PTDIEN != value))
				{
					this._TEN_PTDIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAI_PTDIEN", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string LOAI_PTDIEN
		{
			get
			{
				return this._LOAI_PTDIEN;
			}
			set
			{
				if ((this._LOAI_PTDIEN != value))
				{
					this._LOAI_PTDIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_PMISCHA", DbType="NVarChar(50)")]
		public string MA_PMISCHA
		{
			get
			{
				return this._MA_PMISCHA;
			}
			set
			{
				if ((this._MA_PMISCHA != value))
				{
					this._MA_PMISCHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SCADA", DbType="NVarChar(50)")]
		public string MA_SCADA
		{
			get
			{
				return this._MA_SCADA;
			}
			set
			{
				if ((this._MA_SCADA != value))
				{
					this._MA_SCADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CMIS", DbType="NVarChar(50)")]
		public string MA_CMIS
		{
			get
			{
				return this._MA_CMIS;
			}
			set
			{
				if ((this._MA_CMIS != value))
				{
					this._MA_CMIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANG_THAI", DbType="Int")]
		public System.Nullable<int> TRANG_THAI
		{
			get
			{
				return this._TRANG_THAI;
			}
			set
			{
				if ((this._TRANG_THAI != value))
				{
					this._TRANG_THAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOI_DIEM", DbType="DateTime")]
		public System.Nullable<System.DateTime> THOI_DIEM
		{
			get
			{
				return this._THOI_DIEM;
			}
			set
			{
				if ((this._THOI_DIEM != value))
				{
					this._THOI_DIEM = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
